services:
  # PHP App & Composer
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: jphomepage_app
    volumes:
      - .:/var/www
    networks:
      - jphomepage_net

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: jphomepage_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - jphomepage_net

  # MariaDB
  mariadb:
    image: mariadb:10.11
    container_name: jphomepage_mariadb
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    environment:      
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - jphomepage_net

  # Redis
  redis:
    image: redis:alpine
    container_name: jphomepage_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      - jphomepage_net

  # Composer Helper (Zum Ausführen von Composer Befehlen)
  composer:
    image: composer:2
    container_name: jphomepage_composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ["composer"]

  # NPM Helper (Optional, zum Ausführen von npm Befehlen)
  npm:
    image: node:20
    container_name: jphomepage_npm
    volumes:
      - .:/var/www
    working_dir: /var/www
    entrypoint: ["npm"]
    networks:
      - jphomepage_net
  npm-vite-server:
    image: node:20
    container_name: jphomepage_npm_vite_server
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    networks:
      - jphomepage_net

networks:
  jphomepage_net:
    driver: bridge

volumes:
  db_data: